package core

import model "github.com/Viking602/go-hydaelyn/internal/core/model"

var (
	ErrNotFound                = model.ErrNotFound
	ErrTerminalState           = model.ErrTerminalState
	ErrStaleTaskVersion        = model.ErrStaleTaskVersion
	ErrLeaseHolderMismatch     = model.ErrLeaseHolderMismatch
	ErrLeaseNotActive          = model.ErrLeaseNotActive
	ErrOwnerMismatch           = model.ErrOwnerMismatch
	ErrActionTaskRequired      = model.ErrActionTaskRequired
	ErrActionReconcileRequired = model.ErrActionReconcileRequired
	ErrResponseTaskRequired    = model.ErrResponseTaskRequired
	ErrPolicyDenied            = model.ErrPolicyDenied
	ErrPolicyObligationFailed  = model.ErrPolicyObligationFailed
	ErrFlowBypass              = model.ErrFlowBypass
	ErrHandoffCycle            = model.ErrHandoffCycle
	ErrHandoffDepthExceeded    = model.ErrHandoffDepthExceeded
	ErrInvalidCommand          = model.ErrInvalidCommand
	ErrInvalidTransition       = model.ErrInvalidTransition
	ErrCompletionCriteriaUnmet = model.ErrCompletionCriteriaUnmet
	ErrDependencyUnmet         = model.ErrDependencyUnmet
	ErrDependencyFailed        = model.ErrDependencyFailed
	ErrInvalidConfiguration    = model.ErrInvalidConfiguration
)

const (
	ToolEffectReadOnly                       = model.ToolEffectReadOnly
	ToolEffectWrite                          = model.ToolEffectWrite
	ToolEffectExternalSideEffect             = model.ToolEffectExternalSideEffect
	BlackboardVisibilityInternal             = model.BlackboardVisibilityInternal
	BlackboardVisibilityAgentVisible         = model.BlackboardVisibilityAgentVisible
	BlackboardVisibilityUserVisibleCandidate = model.BlackboardVisibilityUserVisibleCandidate
	BlackboardVisibilityUserVisible          = model.BlackboardVisibilityUserVisible
	BlackboardItemClaim                      = model.BlackboardItemClaim
	BlackboardItemEvidence                   = model.BlackboardItemEvidence
	BlackboardItemFinding                    = model.BlackboardItemFinding
	BlackboardItemArtifactRef                = model.BlackboardItemArtifactRef
	BlackboardItemContext                    = model.BlackboardItemContext
	BlackboardItemTaskOutput                 = model.BlackboardItemTaskOutput
	BlackboardItemHandoffContext             = model.BlackboardItemHandoffContext
	SourceAgent                              = model.SourceAgent
	SourceComponent                          = model.SourceComponent
	SourceTool                               = model.SourceTool
	SourceSystem                             = model.SourceSystem
	EventRunStarted                          = model.EventRunStarted
	EventRunStatusChanged                    = model.EventRunStatusChanged
	EventIntentAnalyzed                      = model.EventIntentAnalyzed
	EventPlanCreated                         = model.EventPlanCreated
	EventPlanValidated                       = model.EventPlanValidated
	EventRoutingPlanCreated                  = model.EventRoutingPlanCreated
	EventTaskCreated                         = model.EventTaskCreated
	EventTaskDispatched                      = model.EventTaskDispatched
	EventEnvelopeAcked                       = model.EventEnvelopeAcked
	EventEnvelopeDeadLettered                = model.EventEnvelopeDeadLettered
	EventTaskExecutionAcquired               = model.EventTaskExecutionAcquired
	EventTaskExecutionHeartbeat              = model.EventTaskExecutionHeartbeat
	EventTaskExecutionReleased               = model.EventTaskExecutionReleased
	EventTypedReportSubmitted                = model.EventTypedReportSubmitted
	EventTaskCompleted                       = model.EventTaskCompleted
	EventTaskFailed                          = model.EventTaskFailed
	EventTaskBlocked                         = model.EventTaskBlocked
	EventTaskPaused                          = model.EventTaskPaused
	EventUserInputSubmitted                  = model.EventUserInputSubmitted
	EventResumeTokenCreated                  = model.EventResumeTokenCreated
	EventActionReconcileRequired             = model.EventActionReconcileRequired
	EventActionAttemptStarted                = model.EventActionAttemptStarted
	EventActionAttemptUpdated                = model.EventActionAttemptUpdated
	EventBlackboardItemWritten               = model.EventBlackboardItemWritten
	EventHandoffRequested                    = model.EventHandoffRequested
	EventHandoffApplied                      = model.EventHandoffApplied
	EventHandoffEnvelopeQueued               = model.EventHandoffEnvelopeQueued
	EventApprovalRequested                   = model.EventApprovalRequested
	EventApprovalDecided                     = model.EventApprovalDecided
	EventTaskOwnerChanged                    = model.EventTaskOwnerChanged
	EventPolicyObligationFailed              = model.EventPolicyObligationFailed
	EventResponseTaskCreated                 = model.EventResponseTaskCreated
	EventSystemResponseBypassAudited         = model.EventSystemResponseBypassAudited
	EventUserMessageComposed                 = model.EventUserMessageComposed
	EventUserMessagePolicyChecked            = model.EventUserMessagePolicyChecked
	EventUserMessageQueued                   = model.EventUserMessageQueued
	EventResponsePublished                   = model.EventResponsePublished
	EventResponsePublishFailed               = model.EventResponsePublishFailed
	EventTaskMonitorDecision                 = model.EventTaskMonitorDecision
	EventMailboxRetryScheduled               = model.EventMailboxRetryScheduled
	EventTraceSpanStarted                    = model.EventTraceSpanStarted
	EventTraceSpanEnded                      = model.EventTraceSpanEnded
	PolicyEffectAllow                        = model.PolicyEffectAllow
	PolicyEffectDeny                         = model.PolicyEffectDeny
	PolicyEffectRequireApproval              = model.PolicyEffectRequireApproval
	PolicyEffectPause                        = model.PolicyEffectPause
	PolicyEffectAbort                        = model.PolicyEffectAbort
	ObligationRedactFields                   = model.ObligationRedactFields
	ObligationSelectorOnly                   = model.ObligationSelectorOnly
	ObligationRequireHumanApproval           = model.ObligationRequireHumanApproval
	ObligationHideInternalTrace              = model.ObligationHideInternalTrace
	ObligationMaskToolOutput                 = model.ObligationMaskToolOutput
	ObligationRestrictHandoffContext         = model.ObligationRestrictHandoffContext
	PolicyOperationDispatch                  = model.PolicyOperationDispatch
	PolicyOperationBlackboardRead            = model.PolicyOperationBlackboardRead
	PolicyOperationBlackboardWrite           = model.PolicyOperationBlackboardWrite
	PolicyOperationHandoff                   = model.PolicyOperationHandoff
	PolicyOperationToolCall                  = model.PolicyOperationToolCall
	PolicyOperationAction                    = model.PolicyOperationAction
	PolicyOperationResponseCompose           = model.PolicyOperationResponseCompose
	PolicyOperationResponsePublish           = model.PolicyOperationResponsePublish
	ReplayModeAudit                          = model.ReplayModeAudit
	ReplayModeRecovery                       = model.ReplayModeRecovery
	UserMessageComposed                      = model.UserMessageComposed
	UserMessageQueued                        = model.UserMessageQueued
	UserMessagePublished                     = model.UserMessagePublished
	UserMessageFailed                        = model.UserMessageFailed
	UserMessageCancelled                     = model.UserMessageCancelled
	UserMessageTypeFinalAnswer               = model.UserMessageTypeFinalAnswer
	UserMessageTypeProgressUpdate            = model.UserMessageTypeProgressUpdate
	UserMessageTypeApprovalRequest           = model.UserMessageTypeApprovalRequest
	UserMessageTypeClarificationRequest      = model.UserMessageTypeClarificationRequest
	UserMessageTypeExecutionResult           = model.UserMessageTypeExecutionResult
	UserMessageTypeErrorNotice               = model.UserMessageTypeErrorNotice
	UserMessageTypeBlockedNotice             = model.UserMessageTypeBlockedNotice
	RunStatusCreated                         = model.RunStatusCreated
	RunStatusPlanning                        = model.RunStatusPlanning
	RunStatusValidating                      = model.RunStatusValidating
	RunStatusRouting                         = model.RunStatusRouting
	RunStatusDispatching                     = model.RunStatusDispatching
	RunStatusRunning                         = model.RunStatusRunning
	RunStatusWaitingUserInput                = model.RunStatusWaitingUserInput
	RunStatusWaitingApproval                 = model.RunStatusWaitingApproval
	RunStatusExecuting                       = model.RunStatusExecuting
	RunStatusReconcileRequired               = model.RunStatusReconcileRequired
	RunStatusComposingResponse               = model.RunStatusComposingResponse
	RunStatusCompleted                       = model.RunStatusCompleted
	RunStatusFailed                          = model.RunStatusFailed
	RunStatusBlocked                         = model.RunStatusBlocked
	RunStatusCancelled                       = model.RunStatusCancelled
	TaskTypeWorker                           = model.TaskTypeWorker
	TaskTypeResponse                         = model.TaskTypeResponse
	AwaitModeAll                             = model.AwaitModeAll
	AwaitModeAny                             = model.AwaitModeAny
	AwaitModeQuorum                          = model.AwaitModeQuorum
	OnDependencyFailedContinue               = model.OnDependencyFailedContinue
	OnDependencyFailedSkip                   = model.OnDependencyFailedSkip
	OnDependencyFailedFail                   = model.OnDependencyFailedFail
	TaskStatusCreated                        = model.TaskStatusCreated
	TaskStatusPlanned                        = model.TaskStatusPlanned
	TaskStatusValidated                      = model.TaskStatusValidated
	TaskStatusRouted                         = model.TaskStatusRouted
	TaskStatusWaitingDependency              = model.TaskStatusWaitingDependency
	TaskStatusDispatched                     = model.TaskStatusDispatched
	TaskStatusRunning                        = model.TaskStatusRunning
	TaskStatusPaused                         = model.TaskStatusPaused
	TaskStatusWaitingUserInput               = model.TaskStatusWaitingUserInput
	TaskStatusReconcileRequired              = model.TaskStatusReconcileRequired
	TaskStatusBlocked                        = model.TaskStatusBlocked
	TaskStatusCompleted                      = model.TaskStatusCompleted
	TaskStatusFailed                         = model.TaskStatusFailed
	TaskStatusCancelled                      = model.TaskStatusCancelled
	HolderAgent                              = model.HolderAgent
	HolderComponent                          = model.HolderComponent
	LeaseStatusActive                        = model.LeaseStatusActive
	LeaseStatusReleased                      = model.LeaseStatusReleased
	LeaseStatusExpired                       = model.LeaseStatusExpired
	ReportStatusSuccess                      = model.ReportStatusSuccess
	ReportStatusPartialSuccess               = model.ReportStatusPartialSuccess
	ReportStatusFailed                       = model.ReportStatusFailed
	ReportStatusBlocked                      = model.ReportStatusBlocked
	ReportStatusNeedsHandoff                 = model.ReportStatusNeedsHandoff
	ReportStatusNeedsApproval                = model.ReportStatusNeedsApproval
	ReportStatusNeedsClarification           = model.ReportStatusNeedsClarification
	ActionAttemptCreated                     = model.ActionAttemptCreated
	ActionAttemptRunning                     = model.ActionAttemptRunning
	ActionAttemptSucceeded                   = model.ActionAttemptSucceeded
	ActionAttemptFailed                      = model.ActionAttemptFailed
	ActionAttemptTimeout                     = model.ActionAttemptTimeout
	ActionAttemptUnknown                     = model.ActionAttemptUnknown
	ActionAttemptCancelled                   = model.ActionAttemptCancelled
	TraceSpanStarted                         = model.TraceSpanStarted
	TraceSpanEnded                           = model.TraceSpanEnded
	TraceSpanFailed                          = model.TraceSpanFailed
)

type ToolEffectType = model.ToolEffectType
type ActionOutcome = model.ActionOutcome
type Tool = model.Tool
type RetryPolicy = model.RetryPolicy
type ActionAttempt = model.ActionAttempt
type BlackboardVisibility = model.BlackboardVisibility
type BlackboardItemType = model.BlackboardItemType
type SourceType = model.SourceType
type SourceIdentity = model.SourceIdentity
type BlackboardItem = model.BlackboardItem
type BlackboardSelector = model.BlackboardSelector
type EventType = model.EventType
type Event = model.Event
type Flow = model.Flow
type TaskExecutionLease = model.TaskExecutionLease
type ResumeToken = model.ResumeToken
type HandoffRequest = model.HandoffRequest
type ApprovalRequest = model.ApprovalRequest
type ApprovalDecision = model.ApprovalDecision
type Intent = model.Intent
type TodoPlan = model.TodoPlan
type RoutingPlan = model.RoutingPlan
type TaskRoute = model.TaskRoute
type TaskMonitorDecision = model.TaskMonitorDecision
type PolicyEffect = model.PolicyEffect
type ObligationKind = model.ObligationKind
type PolicyDecision = model.PolicyDecision
type PolicyObligation = model.PolicyObligation
type MessagePolicyChecker = model.MessagePolicyChecker
type PolicyOperation = model.PolicyOperation
type PolicyRequest = model.PolicyRequest
type ReplayMode = model.ReplayMode
type Projection = model.Projection
type ReplaySideEffects = model.ReplaySideEffects
type TypedReport = model.TypedReport
type UserMessageStatus = model.UserMessageStatus
type UserMessageType = model.UserMessageType
type UserMessage = model.UserMessage
type Run = model.Run
type RunStatus = model.RunStatus
type TaskType = model.TaskType
type AwaitMode = model.AwaitMode
type OnDependencyFailed = model.OnDependencyFailed
type TaskStatus = model.TaskStatus
type HolderType = model.HolderType
type LeaseStatus = model.LeaseStatus
type ReportStatus = model.ReportStatus
type ActionAttemptStatus = model.ActionAttemptStatus
type Task = model.Task
type TaskEnvelope = model.TaskEnvelope
type TraceSpanStatus = model.TraceSpanStatus
type TraceSpan = model.TraceSpan
type RunTimelineKind = model.RunTimelineKind
type RunTimelineItem = model.RunTimelineItem

const (
	RunTimelineKindControl  = model.RunTimelineKindControl
	RunTimelineKindWork     = model.RunTimelineKindWork
	RunTimelineKindResponse = model.RunTimelineKindResponse
)
