package api

import "errors"

var (
	ErrNotFound                  = errors.New("orchestrator: not found")
	ErrTerminalState             = errors.New("orchestrator: terminal state")
	ErrStaleTaskVersion          = errors.New("orchestrator: stale task version")
	ErrLeaseHolderMismatch       = errors.New("orchestrator: lease holder mismatch")
	ErrLeaseNotActive            = errors.New("orchestrator: lease not active")
	ErrOwnerMismatch             = errors.New("orchestrator: owner mismatch")
	ErrActionTaskRequired        = errors.New("orchestrator: action task required")
	ErrActionReconcileRequired   = errors.New("orchestrator: action reconcile required")
	ErrIdempotencyConflict       = errors.New("orchestrator: idempotency conflict")
	ErrResponseTaskRequired      = errors.New("orchestrator: response task required")
	ErrPolicyDenied              = errors.New("orchestrator: policy denied")
	ErrPolicyObligationFailed    = errors.New("orchestrator: policy obligation failed")
	ErrDefinitionVersionConflict = errors.New("orchestrator: agent definition version conflict")
	ErrHandoffCycle              = errors.New("orchestrator: handoff owner cycle")
	ErrHandoffDepthExceeded      = errors.New("orchestrator: handoff depth exceeded")
	ErrInvalidCommand            = errors.New("orchestrator: invalid command")
	ErrInvalidTransition         = errors.New("orchestrator: invalid state transition")
	ErrCompletionCriteriaUnmet   = errors.New("orchestrator: completion criteria unmet")
	ErrDependencyUnmet           = errors.New("orchestrator: dependency unmet")
	ErrDependencyFailed          = errors.New("orchestrator: dependency failed")
	ErrCheckpointLimitExceeded   = errors.New("orchestrator: execution checkpoint limit exceeded")
	ErrUsageUnpriced             = errors.New("orchestrator: usage is unpriced")
	ErrInvalidConfiguration      = errors.New("orchestrator: invalid configuration")
	ErrCapabilityNameReserved    = errors.New("orchestrator: capability name is reserved")
	ErrInvalidAddress            = errors.New("orchestrator: invalid address")
	ErrNoRecipients              = errors.New("orchestrator: address resolved to zero recipients")
	ErrSubscriptionClosed        = errors.New("orchestrator: blackboard subscription already closed")
	ErrWaitTimeout               = errors.New("orchestrator: blackboard wait timed out")
)
