<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="testsuites">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="testsuite" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="tests" type="xs:int" use="optional"/>
      <xs:attribute name="failures" type="xs:int" use="optional"/>
      <xs:attribute name="errors" type="xs:int" use="optional"/>
      <xs:attribute name="time" type="xs:decimal" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="testsuite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="testcase" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="tests" type="xs:int" use="required"/>
      <xs:attribute name="failures" type="xs:int" use="optional"/>
      <xs:attribute name="errors" type="xs:int" use="optional"/>
      <xs:attribute name="skipped" type="xs:int" use="optional"/>
      <xs:attribute name="time" type="xs:decimal" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="testcase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="failure" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="classname" type="xs:string" use="optional"/>
      <xs:attribute name="time" type="xs:decimal" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="failure">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="message" type="xs:string" use="optional"/>
          <xs:attribute name="type" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>
